# Generated by Django 3.0 on 2019-12-06 07:35

from django.db import migrations, models

import xmltables.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IatiActivities",
            fields=[
                ("aims_id", models.TextField(primary_key=True, serialize=False)),
                ("iati_identifier", models.TextField()),
                ("content", xmltables.models.XmlField()),
            ],
        )
    ]
