# Generated by Django 3.0 on 2019-12-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("iatistore", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="iatiactivities", old_name="aims_id", new_name="id"
        )
    ]
