# Generated by Django 3.0 on 2019-12-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("iatistore", "0003_narrativexmltable")]

    operations = [
        migrations.AddField(
            model_name="narrativexmltable",
            name="narrative_type",
            field=models.CharField(default="", max_length=512),
            preserve_default=False,
        )
    ]
