# Generated by Django 3.0 on 2020-01-17 01:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import xmltables.models


class Migration(migrations.Migration):

    dependencies = [
        ('iatistore', '0007_slugify'),
    ]

    operations = [
        migrations.CreateModel(
            name='IatiCodelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', xmltables.models.XmlField()),
                ('iati_version', models.DecimalField(decimal_places=2, max_digits=3)),
                ('complete', models.BooleanField()),
                ('embedded', models.BooleanField()),
                ('name', django.contrib.postgres.fields.jsonb.JSONField()),
                ('description', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
