# Generated by Django 3.0 on 2020-01-17 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iatistore", "0008_iaticodelist"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="iaticodelist",
            unique_together={("iati_version", "label")},
        ),
    ]
