# Generated by Django 3.0 on 2020-01-17 02:58

from django.db import migrations, models
import xmltables.models


class Migration(migrations.Migration):

    dependencies = [
        ('iatistore', '0009_auto_20200117_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iaticodelist',
            name='content',
            field=xmltables.models.XmlField(null=True),
        ),
        migrations.AlterField(
            model_name='iaticodelist',
            name='embedded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='iaticodelist',
            name='iati_version',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
