# Generated by Django 3.0 on 2020-01-17 03:07

from django.db import migrations, models
import xmltables.models


class Migration(migrations.Migration):

    dependencies = [
        ("iatistore", "0010_auto_20200117_0258"),
    ]

    operations = [
        migrations.CreateModel(
            name="IatiCodelistMapping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", xmltables.models.XmlField(null=True)),
                (
                    "iati_version",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
            ],
        ),
    ]
