# Generated by Django 3.0 on 2020-01-22 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iatistore', '0014_iaticodelistitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='iaticodelistitem',
            unique_together={('codelist', 'code')},
        ),
    ]
