# Generated by Django 3.0 on 2020-01-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iatistore', '0015_auto_20200122_0630'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='iaticodelistitem',
            index=models.Index(fields=['codelist', 'code'], name='iatistore_i_codelis_41170f_idx'),
        ),
    ]
